export const {
  TOKEN,
  // OpenAI
  OPENAI_API_KEY,

  // OpenRouter
  OPENROUTER_API_KEY,
  OPENROUTER_BASE_URL,

  // Ollama
  OLLAMA_HOST,
  OLLAMA_MODEL,

  SECURITY_JWT_SECRET,

  // External URLs
  FRONTEND_URL,

  // Relational Database
  RELATIONAL_DB_TYPE,
  RELATIONAL_DB_HOST,
  RELATIONAL_DB_PORT,
  RELATIONAL_DB_USERNAME,
  RELATIONAL_DB_PASSWORD,
  RELATIONAL_DB_DATABASE,
  RELATIONAL_DB_LOGGING,
} = process.env;
